apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-api-provider-vsphere-ci
spec:
  backoffLimit: 4
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: cluster-api-provider-vsphere-ci
        image: luoh/cluster-api-provider-vsphere-ci:latest
        volumeMounts:
          - name: kube
            mountPath: /root/.kube
          - name: envs
            mountPath: /root/.config
          - name: sshkeys
            mountPath: /root/.ssh
        command:
        - "./clusterctl.sh"
        args:
        - /root/config/envs
      volumes:
      - name: kube
        hostPath:
          path: /home/vmware/.kube
      - name: envs
        hostPath:
          path: /home/vmware/.config
      - name: sshkeys
        hostPath:
          path: /home/vmware/.ssh
      restartPolicy: Never
